jobs:
#############################################
- job: Windows_build
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: azure-pipeline-templates/dotnet-core-steps.yml
 #############################################
- job: macOS_build
  dependsOn: Windows_build
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: azure-pipeline-templates/dotnet-core-steps.yml
  
 #############################################
- job: Linux_build
  dependsOn: macOS_build
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: azure-pipeline-templates/dotnet-core-steps.yml